package com.halotroop.mocreatures.common.registry;

import com.halotroop.mocreatures.common.MoCMain;
import net.minecraft.sound.SoundEvent;
import net.minecraft.util.Identifier;
import net.minecraft.util.registry.Registry;

import java.util.Locale;

public class MoCSoundEvents {
	public enum Sounds {
		BEAR_AMBIENT, BEAR_DEATH, BEAR_HURT,
		BEE_AMBIENT, BEE_UPSET,
		BIRD_AMBIENT_BLACK, BIRD_AMBIENT_BLUE, BIRD_AMBIENT_GREEN,
		BIRD_AMBIENT_RED, BIRD_AMBIENT_WHITE, BIRD_AMBIENT_YELLOW,
		BIRD_DEATH, BIRD_HURT,
		CRICKET_AMBIENT, CRICKET_FLY, CROCODILE_AMBIENT,
		CROCODILE_DEATH, CROCODILE_HURT, CROCODILE_JAWSNAP, CROCODILE_RESTING, CROCODILE_ROLL,
		DEER_AMBIENT_BABY, DEER_AMBIENT, DEER_DEATH, DEER_HURT,
		DOLPHIN_UPSET,
		DUCK_AMBIENT, DUCK_DEATH, DUCK_HURT,
		DRAGONFLY_AMBIENT,
		ELEPHANT_AMBIENT_BABY, ELEPHANT_AMBIENT, ELEPHANT_DEATH, ELEPHANT_HURT,
		ENT_AMBIENT, ENT_DEATH, ENT_HURT,
		FLY_AMBIENT,
		GENERIC_ARMOR_ON, GENERIC_ARMOR_OFF,
		GENERIC_DESTROY,
		GENERIC_DRINKING,
		GENERIC_EATING,
		GENERIC_MAGIC_APPEAR,
		GENERIC_ROPING,
		GENERIC_TRANSFORM,
		GENERIC_THUD,
		GENERIC_VANISH,
		GENERIC_WHIP,
		GENERIC_WINGFLAP,
		GOAT_AMBIENT, GOAT_AMBIENT_BABY, GOAT_AMBIENT_FEMALE, GOAT_DEATH, GOAT_DIGG, GOAT_EATING, GOAT_HURT, GOAT_SMACK,
		GOLEM_AMBIENT, GOLEM_ATTACH, GOLEM_DYING, GOLEM_EXPLODE, GOLEM_HURT, GOLEM_SHOOT, GOLEM_WALK,
		//		KITTY_AMBIENT, KITTY_AMBIENT_BABY, KITTY_ANGRY, KITTY_DEATH, KITTY_DEATH_BABY, KITTY_DRINKING, KITTY_EATING,
//	    KITTY_HUNGRY, KITTY_HURT, KITTY_HURT_BABY, KITTY_PURR, KITTY_TRAPPED,
		KITTY_LITTER,
		KITTYBED_POURINGMILK,
		KITTYBED_POURINGFOOD,
		LION_AMBIENT, LION_AMBIENT_BABY, LION_DEATH, LION_DEATH_BABY, LION_HURT, LION_HURT_BABY,
		MOUSE_AMBIENT, MOUSE_DEATH, MOUSE_HURT,
		OGRE_AMBIENT, OGRE_DEATH, OGRE_HURT,
		OSTRICH_AMBIENT, OSTRICH_AMBIENT_BABY, OSTRICH_DEATH, OSTRICH_HURT,
		RABBIT_LIFT,
		RACCOON_AMBIENT, RACCOON_DEATH, RACCOON_HURT,
		RAT_AMBIENT, RAT_DEATH, RAT_HURT,
		SCORPION_AMBIENT, SCORPION_CLAW, SCORPION_DEATH, SCORPION_HURT, SCORPION_STING,
		SNAKE_AMBIENT, SNAKE_ANGRY, SNAKE_DEATH, SNAKE_HURT, SNAKE_RATTLE, SNAKE_SNAP, SNAKE_SWIM,
		TURKEY_AMBIENT, TURKEY_HURT,
		TURTLE_ANGRY, TURTLE_EATING,
		WEREWOLF_AMBIENT, WEREWOLF_AMBIENT_HUMAN, WEREWOLF_DEATH, WEREWOLF_DEATH_HUMAN, WEREWOLF_HURT_HUMAN,
		WEREWOLF_HURT, WEREWOLF_TRANSFORM,
		WRAITH_AMBIENT, WRAITH_DEATH, WRAITH_HURT,
		WYVERN_AMBIENT, WYVERN_DEATH, WYVERN_HURT, WYVERN_WINGFLAP;
		
		public SoundEvent event;
	}
	
	public static SoundEvent ITEM_RECORD_SHUFFLING;
	
	public static void registerAll() {
		for (Sounds sound : Sounds.values()) {
			sound.event = register(sound.name().toLowerCase(Locale.ENGLISH).replaceAll("_", ""));
		}
		ITEM_RECORD_SHUFFLING = register("shuffling");
	}
	
	private static SoundEvent register(String name) {
		Identifier id = MoCMain.getID(name);
		return Registry.register(Registry.SOUND_EVENT, id, new SoundEvent(id));
	}
}
